name: 04_exercicio

on:
  workflow_dispatch:



jobs:
  deployment:
    
    runs-on: self-hosted
    environment: 
      name: PRODUCAO
      url: https://github.com
      
      
    steps:
      - name: 'Print secret from environment'
        run: |
            echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"
